title: Standardseite
icon: page

navigation:
  status: all
  template: all

tabs:
  content:
    label: Seite
    icon: document
    columns:
      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              blocks:
                extends: fields/blocks
      - width: 1/3
        sections:
          pages:
            headline: Seiten
            type: pages
            template: default
            image:
              back: black

  files:
    extends: tabs/files
  seo:
    extends: tabs/seo
