# Template witout file-structure
title: Projekt
icon: star

navigation:
  status: all

options:
  move: false

image:
  query: page.images.template("cover").first
  back: black
  cover: true

tabs:
  content:
    label: Seite
    icon: document
    columns:
      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              headline:
                label: Headline
                type: textarea
                buttons: false
              text:
                label: Text
                extends: fields/writer
          gallery:
            headline: Bildergalerie
            type: files
            template: image
            layout: cards
            info: "{{ file.alt }}"
            size: small
            batch: true
            image:
              back: black

      - width: 1/3
        sections:
          cover:
            extends: sections/cover
          downloads:
            headline: Downloads
            type: files
            template: file
            info: "{{ file.description }}"
            empty: Kein Dateien
            batch: true
            image:
              back: black

  seo:
    extends: tabs/seo
