title: Standardseite
icon: page

tabs:
  content:
    label: Seite
    icon: document
    columns:
      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              headline:
                label: Headline
                type: textarea
                buttons: false
              text:
                label: Text
                extends: fields/writer
              blocks:
                extends: fields/blocks
      - width: 1/3
        sections:
          cover:
            headline: Cover
            type: files
            template: cover
            max: 1
            layout: cards
            image:
              back: black
          pages:
            headline: Seiten
            type: pages
            template: rubrik
            image:
              back: black
          images:
            headline: Bilder
            type: files
            template: image
            image:
              back: black
          files:
            headline: Dateien
            type: files
            template: file
            info: '{{ file.description }}'
            image:
              back: black

  files:
    extends: tabs/files
  seo:
    extends: tabs/seo
