title: Default Page
icon: page

columns:
  - width: 2/3
    sections:
      content:
        type: fields
        fields:
          headline:
            label: Headline
            type: textarea
            buttons: false
          text:
            label: Text
            extends: sections/text
  - width: 1/3
    sections:
      bild:
        headline: Bild
        type: files
        template: image
        max: 1
        layout: cards
        image:
          ratio: 3/2
          back: white
      pages:
        headline: Rubriken
        type: pages
        template: rubrik
