title: Default Page
icon: page

navigation:
  status: all
  template: all

tabs:
  content:
    label: Inhalt
    icon: document
    columns:
      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              headline:
                label: Headline
                type: textarea
                buttons: false
              text:
                label: Text
                extends: sections/text
      - width: 1/3
        sections:
          bilder:
            headline: Bilder
            type: files
            template: image
            layout: cards
            info: "{{ file.alt }}"
            image:
              back: black
          pages:
            headline: Rubriken
            type: pages
            template: rubrik

  seo:
    label: SEO
    icon: search
    columns:
      - width: 2/3
        fields:
          extends: sections/seo
