title: Projekt
icon: star

options:
  move: false

columns:
  - width: 2/3
    sections:
      content:
        type: fields
        fields:
          headline:
            label: Headline
            type: textarea
            buttons: false
          text:
            label: Text
            extends: fields/writer
  - width: 1/3
    sections:
      date:
        type: fields
        fields:
          date:
            label: Datum
            type: date
            display: DD.MM.YYYY
      cover:
        headline: Cover
        type: files
        template: cover
        max: 1
        layout: cards
        image:
          ratio: 3/2
          cover: true
          back: black
      images:
        headline: Bilder
        type: files
        template: image
        image:
          back: black
      files:
        headline: Dateien
        type: files
        template: file
        sortable: false
        sortBy: name asc
        image:
          back: black
