title: Projekt
icon: star

navigation:
  status: all

options:
  move: false

columns:
  - width: 2/3
    sections:
      content:
        type: fields
        fields:
          headline:
            label: Headline
            type: textarea
            buttons: false
          text:
            label: Text
            extends: fields/writer
  - width: 1/3
    sections:
      cover:
        extends: sections/cover
      date:
        type: fields
        fields:
          date:
            label: Datum
            type: date
            display: DD.MM.YYYY
      images:
        headline: Bildergalerie
        type: files
        template: image
        image:
          back: black
      files:
        headline: Downloads
        type: files
        template: file
        info: '{{ file.description }}'
        image:
          back: black
      videos:
        headline: Videos
        type: files
        template: video
        image:
          back: black

