title: Site

tabs:
  content:
    label: Website
    icon: sitemap
    columns:
      - width: 2/3
        sections:
          projects:
            headline: Projekte
            type: pages
            template: project
            parent: site.find("projects")
            create: project
            status: all
            image:
              query: page.images.findBy("template", "cover")
              cover: true
              back: black
          blog:
            headline: News
            type: pages
            template: post
            parent: site.find("news")
            create: post
            status: all
            info: "{{ page.date.toDate('d.m.Y') }}"
            image:
              query: page.images.findBy("template", "cover")
              cover: true
              back: black
      - width: 1/3
        sections:
          pages:
            headline: Seiten
            create:
              - default
            status: all
            image:
              query: icon
              back: black
  footer:
    label: Footer
    icon: text
    columns:
      - width: 2/3
        fields:
          footer_links:
            label: Links
            type: pages
            image:
              query: icon
              back: black
          footer_address:
            label: Adresse
            type: writer
            nodes: false
            toolbar:
              inline: false
              nodes: false
              marks:
                - bold
                - link
                - email
  seo:
    label: SEO
    icon: search
    columns:
      - width: 2/3
        fields:
          seo_title:
            label: Seitentitel
            type: text
            help: 50 bis 60 Zeichen
          seo_description:
            label: Seitenbeschreibung
            type: textarea
            buttons: false
            help: 100 bis 150 Zeichen
      - width: 1/3
        sections:
          icon:
            headline: Website Icon
            type: files
            template: seo-icon
            multiple: false
            sortable: false
            max: 1
            layout: cards
            help: 1500×1500 Pixel
            image:
              ratio: 1/1
              cover: true
              back: white
          color:
            type: fields
            fields:
              color:
                label: Themenfarbe
                type: color
