title: Site

tabs:
  content:
    label: Website
    icon: text
    sections:
      pages:
        headline: Rubriken
        status: all
  seo:
    label: SEO
    icon: search
    columns:
      left:
        width: 2/3
        fields:
          description:
            label: SEO Beschreibung
            type: textarea
            buttons: false
      right:
        width: 1/3
        fields:
          icon:
            label: Icon
            type: files
            multiple: false
            max: 1
            layout: cards
            image:
              ratio: 1/1
              cover: true
              back: white
            template: icon
            uploads:
              template: icon
