title: Site

tabs:
  content:
    label: Website
    icon: sitemap
    columns:
      - width: 2/3
        sections:
          projekte:
            headline: Projekte
            type: pages
            template: projekt
            parent: site.find("projekt")
            status: all
            image:
              back: black
      - width: 1/3
        sections:
          pages:
            headline: Rubriken
            create: false
            image: false
            status: all
  seo:
    label: SEO
    icon: search
    columns:
      - width: 2/3
        fields:
          seo_description:
            label: SEO Beschreibung
            type: textarea
            buttons: false
            help: 100 bis 150 Zeichen
      - width: 1/3
        sections:
          icon:
            headline: Website Icon
            type: files
            template: seo-icon
            multiple: false
            sortable: false
            max: 1
            layout: cards
            help: 1500×1500 Pixel
            image:
              ratio: 1/1
              cover: true
              back: white
