title: Site

tabs:
  content:
    label: Website
    icon: text
    sections:
      pages:
        headline: Rubriken
        status: all
  seo:
    label: SEO
    icon: search
    columns:
      - width: 2/3
        fields:
          description:
            label: SEO Beschreibung
            type: textarea
            buttons: false
      - width: 1/3
        sections:
          icon:
            label: Website Icon
            type: files
            template: seo-icon
            multiple: false
            sortable: false
            max: 1
            layout: cards
            help: 1500×1500 Pixel
            image:
              ratio: 1/1
              cover: true
              back: white
